In [3]:
# Data Science Foundations – Day 1

## Objective:
# - Understand Jupyter workflow
# - Run Python commands
# - Import NumPy
# - Perform simple calculations

In [4]:
#First python command
print("Hello, Data Science World!")

Hello, Data Science World!


In [5]:
#Basic Calculation
2 + 3

5

In [6]:
10 * 5

50

In [7]:
100 / 4

25.0

In [8]:
#Create Variable

a = 10
b = 5

a + b

15

In [9]:
#Import Numpy
import numpy as np

In [10]:
#Create a numpy Array

arr = np.array([10, 20, 30, 40, 50])

arr

array([10, 20, 30, 40, 50])

In [13]:
#Run Simple Calculations with NumPy
arr * 2

array([ 20,  40,  60,  80, 100])

In [12]:
#find sum
arr.sum()

np.int64(150)

In [14]:
#Find Mean

arr.mean()

np.float64(30.0)

In [15]:
#Find Maximum Value
arr.max()

np.int64(50)

In [16]:
#2D Array (Very Important for ML)

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
matrix.shape

(2, 3)

In [22]:
#Notebook-Based Data Exploration
import pandas as pd

df = pd.read_csv("Dataset/random/sample_data1.csv")
df.head()
df.shape
df.info()
df.describe()
df.isnull().sum()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Employee_ID         15 non-null     int64  
 1   Department          15 non-null     str    
 2   Region              15 non-null     str    
 3   Salary              15 non-null     int64  
 4   Experience_Years    15 non-null     int64  
 5   Performance_Rating  14 non-null     float64
 6   Monthly_Sales       14 non-null     float64
dtypes: float64(2), int64(3), str(2)
memory usage: 1.1 KB


Employee_ID Department Region  Salary  Experience_Years  \
0         1001      Sales  North   45000                 2   
1         1002  Marketing  South   52000                 3   
2         1003      Sales   East   47000                 4   
3         1004         HR   West   40000                 1   
4         1005         IT  North   60000                 5   

   Performance_Rating  Monthly_Sales  
0                 4.0       120000.0  
1                 3.0        98000.0  
2                 5.0       150000.0  
3                 3.0            0.0  
4                 4.0            0.0

In [24]:
#NumPy Arrays

import numpy as np

arr = np.array([1,2,3,4])

arr


array([1, 2, 3, 4])

In [25]:
#Array Operations

arr * 2
arr.mean()
arr.sum()

np.int64(10)

In [26]:
# 2D Arrays (Important for ML)

matrix = np.array([[1,2,3],[4,5,6]])
matrix.shape

(2, 3)

In [1]:
# ================================
# UNIVERSITY STUDENT PERFORMANCE ANALYSIS
# Using: Pandas + NumPy (Built-in Dataset)
# ================================

import pandas as pd
import numpy as np

# -------------------------------
# 1. DATASET CREATION
# -------------------------------

np.random.seed(42)
n_students = 200

df = pd.DataFrame({
    "Student_ID": np.arange(1, n_students + 1),
    "Study_Hours_per_Week": np.random.normal(15, 5, n_students).round(1),
    "Attendance_Percentage": np.random.randint(50, 101, n_students),
    "Assignment_Score": np.random.randint(40, 101, n_students),
    "Midterm_Score": np.random.randint(35, 101, n_students)
})

# Ensure no negative study hours
df["Study_Hours_per_Week"] = df["Study_Hours_per_Week"].clip(lower=0)

# -------------------------------
# 2. FINAL SCORE CALCULATION
# -------------------------------

df["Final_Score"] = (
    0.3 * df["Assignment_Score"] +
    0.3 * df["Midterm_Score"] +
    0.4 * (df["Study_Hours_per_Week"] * 2)
).round(1)

# -------------------------------
# 3. GRADE CLASSIFICATION
# -------------------------------

df["Grade"] = np.where(df["Final_Score"] >= 85, "A",
                np.where(df["Final_Score"] >= 70, "B",
                np.where(df["Final_Score"] >= 55, "C", "Fail")))

# -------------------------------
# 4. AT-RISK IDENTIFICATION
# -------------------------------

df["At_Risk"] = np.where(
    (df["Attendance_Percentage"] < 60) &
    (df["Study_Hours_per_Week"] < 10) &
    (df["Final_Score"] < 55),
    "Yes",
    "No"
)

# -------------------------------
# 5. GROUP CATEGORIZATION
# -------------------------------

df["Attendance_Group"] = np.where(
    df["Attendance_Percentage"] >= 80, "High", "Low"
)

df["Study_Category"] = pd.cut(
    df["Study_Hours_per_Week"],
    bins=[0, 10, 20, 40],
    labels=["Low", "Medium", "High"]
)

# -------------------------------
# 6. ANALYSIS SECTION
# -------------------------------

print("===== BASIC STATISTICS =====")
print("Class Average Final Score:", df["Final_Score"].mean())
print("\nGrade Distribution:\n", df["Grade"].value_counts())

print("\n===== CORRELATION MATRIX =====")
print(df.corr(numeric_only=True))

print("\n===== PERFORMANCE BY ATTENDANCE GROUP =====")
print(df.groupby("Attendance_Group")["Final_Score"].mean())

print("\n===== PERFORMANCE BY STUDY CATEGORY =====")
print(df.groupby("Study_Category")["Final_Score"].mean())

print("\n===== TOP 5 PERFORMERS =====")
print(df.sort_values("Final_Score", ascending=False).head())

print("\n===== BOTTOM 5 PERFORMERS =====")
print(df.sort_values("Final_Score").head())

print("\n===== AT RISK STUDENTS =====")
print(df[df["At_Risk"] == "Yes"].head())

# -------------------------------
# 7. SIMPLE RULE-BASED PREDICTION
# -------------------------------

df["Prediction"] = np.where(
    (df["Study_Hours_per_Week"] > 15) &
    (df["Attendance_Percentage"] > 75),
    "Pass",
    "Risk"
)

accuracy = np.mean(
    ((df["Prediction"] == "Pass") & (df["Final_Score"] >= 55)) |
    ((df["Prediction"] == "Risk") & (df["Final_Score"] < 55))
)

print("\n===== SIMPLE MODEL ACCURACY =====")
print("Accuracy:", round(accuracy * 100, 2), "%")

# -------------------------------
# END OF PROJECT
# -------------------------------

===== BASIC STATISTICS =====
Class Average Final Score: 53.235499999999995

Grade Distribution:
 Grade
Fail    121
C        70
B         9
Name: count, dtype: int64

===== CORRELATION MATRIX =====
                       Student_ID  Study_Hours_per_Week  \
Student_ID               1.000000              0.071390   
Study_Hours_per_Week     0.071390              1.000000   
Attendance_Percentage    0.041718             -0.051039   
Assignment_Score         0.024034             -0.152421   
Midterm_Score           -0.047983              0.057086   
Final_Score              0.011160              0.363039   

                       Attendance_Percentage  Assignment_Score  Midterm_Score  \
Student_ID                          0.041718          0.024034      -0.047983   
Study_Hours_per_Week               -0.051039         -0.152421       0.057086   
Attendance_Percentage               1.000000          0.015418       0.072294   
Assignment_Score                    0.015418          1.000000   